'use client';

import { useState } from 'react';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import { AutodevConfig } from '@/lib/types';
import { saveConfig, startAgent } from '@/lib/api';

interface ReviewLaunchProps {
  config: AutodevConfig;
}

function generateYaml(config: AutodevConfig): string {
  const lines: string[] = ['# autodev.yaml — generated by autodev web UI', ''];

  lines.push(`repo: "${config.repoPath}"`);
  lines.push(`language: ${config.language}`);
  lines.push(`template: ${config.template}`);
  lines.push('');

  lines.push('agent:');
  lines.push(`  type: ${config.agent.type}`);
  if (config.agent.provider) {
    lines.push(`  provider: ${config.agent.provider}`);
  }
  if (config.agent.model) {
    lines.push(`  model: ${config.agent.model}`);
  }
  if (config.agent.apiKey) {
    lines.push(`  api_key: "\${${config.agent.provider === 'anthropic' ? 'ANTHROPIC_API_KEY' : 'OPENAI_API_KEY'}}"`);
  }
  if (config.agent.tool) {
    lines.push(`  tool: ${config.agent.tool}`);
  }
  if (config.agent.toolPath) {
    lines.push(`  tool_path: "${config.agent.toolPath}"`);
  }
  if (config.agent.endpoint) {
    lines.push(`  endpoint: "${config.agent.endpoint}"`);
  }
  lines.push('');

  lines.push('run:');
  lines.push(
    `  max_experiments: ${config.run.maxExperiments === null ? 'null' : config.run.maxExperiments}`,
  );
  lines.push(`  time_limit: "${config.run.timeLimit}"`);
  lines.push(`  aggressiveness: ${config.run.aggressiveness}`);
  lines.push(`  creativity: ${config.run.creativity}`);
  lines.push('');

  lines.push('notifications:');
  lines.push(`  browser: ${config.notifications.browser}`);
  if (config.notifications.email) {
    lines.push(`  email: "${config.notifications.email}"`);
  }
  if (config.notifications.pushover) {
    lines.push('  pushover:');
    lines.push(`    token: "\${PUSHOVER_TOKEN}"`);
    lines.push(`    user: "\${PUSHOVER_USER}"`);
  }

  return lines.join('\n');
}

export default function ReviewLaunch({ config }: ReviewLaunchProps) {
  const [launching, setLaunching] = useState(false);
  const [saving, setSaving] = useState(false);
  const [status, setStatus] = useState<{
    type: 'success' | 'error';
    message: string;
  } | null>(null);

  const yaml = generateYaml(config);

  const providerLabel = (() => {
    switch (config.agent.type) {
      case 'api-key':
        return `${config.agent.provider || 'API'} (${config.agent.model || 'default'})`;
      case 'local-cli':
        return `CLI: ${config.agent.tool || 'unknown'}`;
      case 'local-inference':
        return `Local (${config.agent.model || 'default'})`;
      default:
        return config.agent.type;
    }
  })();

  const timeLimitLabel: Record<string, string> = {
    '1h': '1 hour',
    '4h': '4 hours',
    '8h': '8 hours (overnight)',
    none: 'No limit',
  };

  async function handleLaunch() {
    setLaunching(true);
    setStatus(null);
    try {
      await saveConfig(config as unknown as Record<string, unknown>);
      await startAgent({
        repoPath: config.repoPath,
        template: config.template,
        language: config.language,
        agent: config.agent,
        run: config.run,
      });
      window.location.href = '/dashboard/';
    } catch (err) {
      setStatus({
        type: 'error',
        message: err instanceof Error ? err.message : 'Failed to launch',
      });
      setLaunching(false);
    }
  }

  async function handleSave() {
    setSaving(true);
    setStatus(null);
    try {
      const result = await saveConfig(config as unknown as Record<string, unknown>);
      setStatus({
        type: 'success',
        message: `Configuration saved to ${result.configPath}`,
      });
    } catch (err) {
      setStatus({
        type: 'error',
        message: err instanceof Error ? err.message : 'Failed to save',
      });
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div>
        <h2 className="text-2xl font-bold mb-2">Review &amp; Launch</h2>
        <p className="text-zinc-500 text-sm">
          Double-check your settings, then let autodev do its thing.
        </p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4">
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Repository
          </p>
          <p className="text-sm font-medium text-zinc-200 font-mono truncate">
            {config.repoPath || 'Not selected'}
          </p>
        </Card>
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Language
          </p>
          <p className="text-sm font-medium text-zinc-200 capitalize">
            {config.language || 'Not selected'}
          </p>
        </Card>
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Agent
          </p>
          <p className="text-sm font-medium text-zinc-200">{providerLabel}</p>
        </Card>
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Experiments
          </p>
          <p className="text-sm font-medium text-zinc-200">
            {config.run.maxExperiments === null
              ? 'Unlimited'
              : config.run.maxExperiments}
          </p>
        </Card>
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Time Limit
          </p>
          <p className="text-sm font-medium text-zinc-200">
            {timeLimitLabel[config.run.timeLimit] || config.run.timeLimit}
          </p>
        </Card>
        <Card>
          <p className="text-xs text-zinc-500 uppercase tracking-wider mb-1">
            Style
          </p>
          <p className="text-sm font-medium text-zinc-200 capitalize">
            {config.run.aggressiveness} / {config.run.creativity}
          </p>
        </Card>
      </div>

      {/* Notifications summary */}
      <Card>
        <p className="text-xs text-zinc-500 uppercase tracking-wider mb-2">
          Notifications
        </p>
        <div className="flex flex-wrap gap-2">
          {config.notifications.browser && (
            <span className="text-xs bg-emerald-500/10 text-emerald-400 px-2 py-1 rounded">
              Browser
            </span>
          )}
          {config.notifications.email && (
            <span className="text-xs bg-emerald-500/10 text-emerald-400 px-2 py-1 rounded">
              Email: {config.notifications.email}
            </span>
          )}
          {config.notifications.pushover && (
            <span className="text-xs bg-emerald-500/10 text-emerald-400 px-2 py-1 rounded">
              Pushover
            </span>
          )}
          {!config.notifications.browser &&
            !config.notifications.email &&
            !config.notifications.pushover && (
              <span className="text-xs text-zinc-600">None configured</span>
            )}
        </div>
      </Card>

      {/* YAML preview */}
      <div>
        <p className="text-sm font-medium text-zinc-400 mb-3">
          Generated Configuration
        </p>
        <div className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden">
          <div className="flex items-center gap-2 px-4 py-2.5 bg-zinc-900 border-b border-zinc-800">
            <span className="w-3 h-3 rounded-full bg-zinc-700" />
            <span className="w-3 h-3 rounded-full bg-zinc-700" />
            <span className="w-3 h-3 rounded-full bg-zinc-700" />
            <span className="ml-3 text-xs text-zinc-600 font-mono">
              autodev.yaml
            </span>
          </div>
          <pre className="p-5 code-block overflow-x-auto text-sm leading-relaxed">
            {yaml.split('\n').map((line, i) => {
              // Simple YAML syntax highlighting
              if (line.startsWith('#')) {
                return (
                  <div key={i}>
                    <span className="comment">{line}</span>
                  </div>
                );
              }
              const match = line.match(/^(\s*)([\w_]+):(.*)/);
              if (match) {
                const [, indent, key, val] = match;
                let valEl: React.ReactNode = val;
                const trimmed = val.trim();
                if (trimmed.startsWith('"') || trimmed.startsWith("'")) {
                  valEl = <span className="string">{val}</span>;
                } else if (/^\s*\d/.test(val) || trimmed === 'null') {
                  valEl = <span className="number">{val}</span>;
                } else if (trimmed === 'true' || trimmed === 'false') {
                  valEl = <span className="number">{val}</span>;
                }
                return (
                  <div key={i}>
                    {indent}
                    <span className="key">{key}</span>:{valEl}
                  </div>
                );
              }
              return <div key={i}>{line}</div>;
            })}
          </pre>
        </div>
      </div>

      {/* Status messages */}
      {status && (
        <div
          className={`text-sm rounded-lg px-4 py-3 ${
            status.type === 'success'
              ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
              : 'bg-red-500/10 text-red-400 border border-red-500/20'
          }`}
        >
          {status.message}
        </div>
      )}

      {/* Launch buttons */}
      <div className="space-y-3 pt-2">
          <Button
            size="lg"
            className="w-full animate-pulse-glow"
            onClick={handleLaunch}
            loading={launching}
          >
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" />
            </svg>
            Launch autodev
          </Button>
          <Button
            variant="secondary"
            size="md"
            className="w-full"
            onClick={handleSave}
            loading={saving}
          >
            Save Config Only
          </Button>
        </div>
    </div>
  );
}
